export const ARSIP_CONFIG = {
  renstra: {
    kode: "03.02.01",
    jenis: "renstra",
    jenisLabel: "Renstra LPPM",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/kebijakan/renstra-lppm",
    listRoute: "/klasifikasi/kebijakan/renstra-lppm",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  roadmap: {
    kode: "03.02.01",
    jenis: "roadmap",
    jenisLabel: "Roadmap",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/kebijakan/roadmap",
    listRoute: "/klasifikasi/kebijakan/roadmap",
    icon: "ti-building-bank",
    bg: "#E9EEFB",
    fg: "#2E5AAC",
  },
  skReviewer: {
    kode: "03.02.02",
    jenis: "sk-reviewer",
    jenisLabel: "SK Reviewer",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/peraturan/sk-reviewer",
    listRoute: "/klasifikasi/peraturan/sk-reviewer",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  skLppm: {
    kode: "03.02.02",
    jenis: "sk-lppm",
    jenisLabel: "SK LPPM",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/peraturan/sk-lppm",
    listRoute: "/klasifikasi/peraturan/sk-lppm",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  dipa: {
    kode: "03.02.03",
    jenis: "dipa",
    jenisLabel: "DIPA",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/keuangan/dipa",
    listRoute: "/klasifikasi/keuangan/dipa",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  rka: {
    kode: "03.02.03",
    jenis: "rka",
    jenisLabel: "RKA",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/keuangan/rka",
    listRoute: "/klasifikasi/keuangan/rka",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  rkakl: {
    kode: "03.02.03",
    jenis: "rkakl",
    jenisLabel: "RKAKL",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/keuangan/rkakl",
    listRoute: "/klasifikasi/keuangan/rkakl",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  spjHibah: {
    kode: "03.02.04",
    jenis: "spj-hibah",
    jenisLabel: "SPJ Hibah",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/keuangan/spj-hibah",
    listRoute: "/klasifikasi/keuangan/spj-hibah",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  kwitansi: {
    kode: "03.02.04",
    jenis: "kwitansi",
    jenisLabel: "Kwitansi",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/keuangan/kwitansi",
    listRoute: "/klasifikasi/keuangan/kwitansi",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  proposalPenelitianinternal: {
    kode: "03.02.05",
    jenis: "proposal-penelitian-internal",
    jenisLabel: "PROPOSAL",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/penelitian/proposal-penelitian-internal",
    listRoute: "/klasifikasi/penelitian/proposal-penelitian-internal",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  skPenelitian: {
    kode: "03.02.05",
    jenis: "sk-penelitian",
    jenisLabel: "SK",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/penelitian/sk-penelitain",
    listRoute: "/klasifikasi/penelitian/sk-penelitain",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  kontrakPenelitian: {
    kode: "03.02.05",
    jenis: "kontrak-penelitian",
    jenisLabel: "KONTRAK",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/penelitian/kontrak-penelitain",
    listRoute: "/klasifikasi/penelitian/kontrak-penelitain",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  laporanPenelitian: {
    kode: "03.02.05",
    jenis: "laporan-penelitian",
    jenisLabel: "LAPORAN",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/penelitian/laporan-penelitain",
    listRoute: "/klasifikasi/penelitian/laporan-penelitain",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  proposalPenelitianeksternal: {
    kode: "03.02.06",
    jenis: "proposal-penelitian-eksternal",
    jenisLabel: "PROPOSAL",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/penelitian/proposal-penelitian-eksternal",
    listRoute: "/klasifikasi/penelitian/proposal-penelitian-eksternal",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  kontrakInduk: {
    kode: "03.02.06",
    jenis: "kontrak-induk",
    jenisLabel: "KONTRAK INDUK",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/penelitian/kontrak-induk",
    listRoute: "/klasifikasi/penelitian/kontrak-induk",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  kontrakTurunan: {
    kode: "03.02.06",
    jenis: "kontrak-turunan",
    jenisLabel: "KONTRAK TURUNAN",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/penelitian/kontrak-turunan",
    listRoute: "/klasifikasi/penelitian/kontrak-turunan",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  laporanKemajuan: {
    kode: "03.02.06",
    jenis: "laporan-kemajuan",
    jenisLabel: "LAPORAN KEMAJUAN",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/penelitian/laporan-kemajuan",
    listRoute: "/klasifikasi/penelitian/laporan-kemajuan",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  laporanAkhir: {
    kode: "03.02.06",
    jenis: "laporan-akhir",
    jenisLabel: "LAPORAN AKHIR",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/penelitian/laporan-akhir",
    listRoute: "/klasifikasi/penelitian/laporan-akhir",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  mou: {
    kode: "03.02.07",
    jenis: "mou",
    jenisLabel: "MoU",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/penelitian/mou",
    listRoute: "/klasifikasi/penelitian/mou",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  moa: {
    kode: "03.02.07",
    jenis: "moa",
    jenisLabel: "MoA",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/penelitian/moa",
    listRoute: "/klasifikasi/penelitian/moa",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  kontrakKerjasama: {
    kode: "03.02.07",
    jenis: "kontrak-kerjasama",
    jenisLabel: "KONTRAK KERJASAMA",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/penelitian/kontrak-kerjasamapenelitian",
    listRoute: "/klasifikasi/penelitian/kontrak-kerjasamapenelitian",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  proposalPengabdianinternal: {
    kode: "03.02.08",
    jenis: "proposal-pengabdian-internal",
    jenisLabel: "PROPOSAL",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/pengabdian/proposal-pengabdian-internal",
    listRoute: "/klasifikasi/pengabdian/proposal-pengabdian-internal",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  skPengabdian: {
    kode: "03.02.08",
    jenis: "sk-pengabdian",
    jenisLabel: "SK",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/pengabdian/sk-pengabdian",
    listRoute: "/klasifikasi/pengabdian/sk-pengabdian",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  kontrakPengabdian: {
    kode: "03.02.08",
    jenis: "kontrak-pengabdian",
    jenisLabel: "KONTRAK PENGABDIAN",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/pengabdian/kontrak-pengabdian",
    listRoute: "/klasifikasi/pengabdian/kontrak-pengabdian",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  laporanPengabdian: {
    kode: "03.02.08",
    jenis: "laporan-pengabdian",
    jenisLabel: "LAPORAN PENGABDIAN",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/pengabdian/laporan-pengabdian",
    listRoute: "/klasifikasi/pengabdian/laporan-pengabdian",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  proposalPengabdianeksternal: {
    kode: "03.02.09",
    jenis: "proposal-pengabdian-eksternal",
    jenisLabel: "PROPOSAL",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/pengabdian/proposal-pengabdian-eksternal",
    listRoute: "/klasifikasi/pengabdian/proposal-pengabdian-eksternal",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  kontrakIndukpengabdian: {
    kode: "03.02.09",
    jenis: "kontrak-induk-pengabdian",
    jenisLabel: "KONTRAK INDUK",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/pengabdian/kontrak-induk-pengabdian",
    listRoute: "/klasifikasi/pengabdian/kontrak-induk-pengabdian",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  kontrakTurunanpengabdian: {
    kode: "03.02.09",
    jenis: "kontrak-turunan-pengabdian",
    jenisLabel: "KONTRAK TURUNAN",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/pengabdian/laporan-turunan-pengabdian",
    listRoute: "/klasifikasi/pengabdian/laporan-turunan-pengabdian",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  laporanKemajuanpengabdian: {
    kode: "03.02.09",
    jenis: "laporan-kemajuan-pengabdian",
    jenisLabel: "LAPORAN KEMAJUAN",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/pengabdian/laporan-kemajuan-pengabdian",
    listRoute: "/klasifikasi/pengabdian/laporan-kemajuan-pengabdian",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  laporanAkhirpengabdian: {
    kode: "03.02.09",
    jenis: "laporan-akhir-pengabdian",
    jenisLabel: "LAPORAN AKHIR",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/pengabdian/laporan-akhir-pengabdian",
    listRoute: "/klasifikasi/pengabdian/laporan-akhir-pengabdian",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  skHki: {
    kode: "03.02.10",
    jenis: "sk-hki",
    jenisLabel: "SK HKI",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/publikasi/sk-hki",
    listRoute: "/klasifikasi/publikasi/sk-hki",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  sertifikatPaten: {
    kode: "03.02.10",
    jenis: "sertifikat-paten",
    jenisLabel: "SERTIFIKAT PATEN",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/publikasi/sertifikat-paten",
    listRoute: "/klasifikasi/publikasi/sertifikat-paten",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  buktiPublikasi: {
    kode: "03.02.10",
    jenis: "bukti-publikasi",
    jenisLabel: "BUKTI PUBLIKASI",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/publikasi/bukti-publikasi",
    listRoute: "/klasifikasi/publikasi/bukti-publikasi",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  skTim: {
    kode: "03.02.11",
    jenis: "sk-tim",
    jenisLabel: "SK TIM",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/administrasi/sk-tim",
    listRoute: "/klasifikasi/administrasi/sk-tim",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  absensi: {
    kode: "03.02.11",
    jenis: "absensi",
    jenisLabel: "ABSENSI",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/administrasi/absensi",
    listRoute: "/klasifikasi/administrasi/absensi",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  skp: {
    kode: "03.02.11",
    jenis: "skp",
    jenisLabel: "SKP",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/administrasi/skp",
    listRoute: "/klasifikasi/administrasi/skp",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  suratMasuk: {
    kode: "03.02.12",
    jenis: "surat-masuk",
    jenisLabel: "SURAT MASUK",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/administrasi/surat-masuk",
    listRoute: "/klasifikasi/administrasi/surat-masuk",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  suratKeluar: {
    kode: "03.02.12",
    jenis: "surat-keluar",
    jenisLabel: "SURAT KELUAR",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/administrasi/surat-keluar",
    listRoute: "/klasifikasi/administrasi/surat-keluar",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  ba: {
    kode: "03.02.12",
    jenis: "ba",
    jenisLabel: "BA",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/administrasi/bk",
    listRoute: "/klasifikasi/administrasi/bk",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  baSerahterimabarang: {
    kode: "03.02.13",
    jenis: "ba-serah-terima-barang",
    jenisLabel: "SERAH TERIMA BARANG",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/administrasi/ba-serah-terima-barang",
    listRoute: "/klasifikasi/administrasi/ba-serah-terima-barang",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  undangan: {
    kode: "03.02.14",
    jenis: "undangan",
    jenisLabel: "UNDANGAN",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/lainnya/undangan",
    listRoute: "/klasifikasi/lainnya/undangan",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  notulen: {
    kode: "03.02.14",
    jenis: "notulen",
    jenisLabel: "NOTULEN",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/lainnya/notulen",
    listRoute: "/klasifikasi/lainnya/notulen",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  foto: {
    kode: "03.02.14",
    jenis: "foto",
    jenisLabel: "FOTO",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/lainnya/foto",
    listRoute: "/klasifikasi/lainnya/foto",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  materi: {
    kode: "03.02.14",
    jenis: "materi",
    jenisLabel: "MATERI",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/lainnya/materi",
    listRoute: "/klasifikasi/lainnya/materi",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  }
};

// Satu bidang = satu halaman listing kartu (misal Kebijakan.jsx).
// jenisKeys merujuk ke key di ARSIP_CONFIG di atas.
export const BIDANG_CONFIG = {
  kebijakan: {
    kode: "03.02.01",
    title: "KEBIJAKAN, RENSTRA, RENJA LPPM",
    tambahRoute: "/uploadkebijakan",
    jenisKeys: ["renstra", "roadmap"],
  },
  peraturan: {
    kode: "03.02.02",
    title: "PERATURAN, SK Ka.LPPM",
    tambahRoute: "/uploadperaturan",
    jenisKeys: ["skReviewer", "skLppm"],
  },
  anggaran: {
    kode: "03.02.03",
    title: "ANGGARAN, DIPA LPPM",
    tambahRoute: "/uploadanggaran",
    jenisKeys: ["dipa", "rka", "rkakl"],
  },
  laporankeuangan: {
    kode: "03.02.04",
    title: "LAPORAN KEUANGAN, SPJ",
    tambahRoute: "/uploadlaporankeuangan",
    jenisKeys: ["spjHibah", "kwitansi"],
  },
  hibahpenelitianinternal: {
    kode: "03.02.05",
    title: "PROPOSAL, SK, KONTRAK, LAPORAN",
    tambahRoute: "/upload-hibah-penelitian-internal",
    jenisKeys: [
      "proposalPenelitianinternal",
      "skPenelitian",
      "kontrakPenelitian",
      "laporanPenelitian",
    ],
  },
  hibahpenelitianeksternal: {
    kode: "03.02.06",
    title:
      "PROPOSAL, KONTRAK INDUK, KONTRAK TURUNAN, LAPORAN KEMAJUAN, LAPORAN AKHIR",
    tambahRoute: "/upload-hibah-penelitian-eksternal",
    jenisKeys: [
      "proposalPenelitianeksternal",
      "kontrakInduk",
      "kontrakTurunan",
      "laporanKemajuan",
      "laporanAkhir",
    ],
  },
  kerjasamapenelitian: {
    kode: "03.02.07",
    title: "MoU, MoA, KONTRAK KERJASAMA",
    tambahRoute: "/upload-kerja-sama",
    jenisKeys: ["mou", "moa", "kontrakKerjasama"],
  },
  hibahpengabdianinternal: {
    kode: "03.02.08",
    title: "PROPOSAL, SK, KONTRAK, LAPORAN",
    tambahRoute: "/upload-hibah-pengabdian-internal",
    jenisKeys: [
      "proposalPengabdianinternal",
      "skPengabdian",
      "kontrakPengabdian",
      "laporanPengabdian",
    ],
  },
  hibahpengabdianeksternal: {
    kode: "03.02.09",
    title:
      "PROPOSAL, KONTRAK INDUK, KONTRAK TURUNAN, LAPORAN KEMAJUAN, LAPORAN AKHIR",
    tambahRoute: "/upload-hibah-pengabdian-eksternal",
    jenisKeys: [
      "proposalPengabdianeksternal",
      "kontrakIndukpengabdian",
      "kontrakTurunanpengabdian",
      "laporanKemajuanpengabdian",
      "laporanAkhirpengabdian",
    ],
  },
  jurnalHkipaten: {
    kode: "03.02.10",
    title: "SK HKI, SERTIFIKAT PATEN, BUKTI PUBLIKASI",
    tambahRoute: "/upload-jurnal-hki-paten",
    jenisKeys: ["skHki", "sertifikatPaten", "buktiPublikasi"],
  },
  kepegawaianLppm: {
    kode: "03.02.11",
    title: "SK TIM, ABSENSI, SKP",
    tambahRoute: "/upload-kepegawaian-lppm",
    jenisKeys: ["skTim", "absensi", "skp"],
  },
  persuratanLppm: {
    kode: "03.02.12",
    title: "SURAT MASUK, SURAT KELUAR, BA",
    tambahRoute: "/upload-persuratan-lppm",
    jenisKeys: ["suratMasuk", "suratKeluar", "ba"],
  },
  saranaPrasaranalppm: {
    kode: "03.02.13",
    title: "BA SERAH TERIMA BARANG",
    tambahRoute: "/upload-sarana-prasarana-lppm",
    jenisKeys: ["baSerahterimabarang"],
  },
  kegiatanSosialisasiworkshopfgd: {
    kode: "03.02.13",
    title: "UNDANGAN, NOTULEN, DOKUMENTASI , MATERI",
    tambahRoute: "/upload-kegiatan-Sosialisasi-Workshop-fgd",
    jenisKeys: ["undangan", "notulen", "foto", "materi"],
  },

  // Contoh nanti buat Peraturan, SK Ka.LPPM (kode 03.02.02):
  // peraturan: {
  //   kode: "03.02.02",
  //   title: "PERATURAN, SK KA.LPPM",
  //   tambahRoute: "/uploadperaturan",
  //   jenisKeys: ["peraturan", "sk-ka-lppm"],
  // },
};
