export const ARSIP_CONFIG = {
  renstra: {
    kode: "03.02.01",
    jenis: "renstra",
    jenisLabel: "Renstra LPPM",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/kebijakan/renstra-lppm",
    listRoute: "/klasifikasi/kebijakan/renstra-lppm",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  roadmap: {
    kode: "03.02.01",
    jenis: "roadmap",
    jenisLabel: "Roadmap",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/kebijakan/roadmap",
    listRoute: "/klasifikasi/kebijakan/roadmap",
    icon: "ti-building-bank",
    bg: "#E9EEFB",
    fg: "#2E5AAC",
  },
    skReviewer: {
    kode: "03.02.02",
    jenis: "sk-reviewer",
    jenisLabel: "SK Reviewer",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/peraturan/sk-reviewer",
    listRoute: "/klasifikasi/peraturan/sk-reviewer",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
    skLppm: {
    kode: "03.02.02",
    jenis: "sk-lppm",
    jenisLabel: "SK LPPM",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/peraturan/sk-lppm",
    listRoute: "/klasifikasi/peraturan/sk-lppm",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  dipa: {
    kode: "03.02.03",
    jenis: "dipa",
    jenisLabel: "DIPA",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/keuangan/dipa",
    listRoute: "/klasifikasi/keuangan/dipa",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  rka: {
    kode: "03.02.03",
    jenis: "rka",
    jenisLabel: "RKA",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/keuangan/rka",
    listRoute: "/klasifikasi/keuangan/rka",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  rkakl: {
    kode: "03.02.03",
    jenis: "rkakl",
    jenisLabel: "RKAKL",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/keuangan/rkakl",
    listRoute: "/klasifikasi/keuangan/rkakl",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  spjHibah: {
    kode: "03.02.04",
    jenis: "spj-hibah",
    jenisLabel: "SPJ Hibah",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/keuangan/spj-hibah",
    listRoute: "/klasifikasi/keuangan/spj-hibah",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },
  kwitansi: {
    kode: "03.02.04",
    jenis: "kwitansi",
    jenisLabel: "Kwitansi",
    hasSubJenis: false,
    metadataFields: [],
    redirectRoute: "/klasifikasi/keuangan/kwitansi",
    listRoute: "/klasifikasi/keuangan/kwitansi",
    icon: "ti-file-analytics",
    bg: "#E7F3EA",
    fg: "#1E8E4F",
  },

};

// Satu bidang = satu halaman listing kartu (misal Kebijakan.jsx).
// jenisKeys merujuk ke key di ARSIP_CONFIG di atas.
export const BIDANG_CONFIG = {
  kebijakan: {
    kode: "03.02.01",
    title: "KEBIJAKAN, RENSTRA, RENJA LPPM",
    tambahRoute: "/uploadkebijakan",
    jenisKeys: ["renstra", "roadmap"],
  },
    peraturan: {
    kode: "03.02.02",
    title: "PERATURAN, SK Ka.LPPM",
    tambahRoute: "/uploadperaturan",
    jenisKeys: ["skReviewer", "skLppm"],
  },
  anggaran: {
    kode: "03.02.03",
    title: "ANGGARAN, DIPA LPPM",
    tambahRoute: "/uploadanggaran",
    jenisKeys: ["dipa", "rka", "rkakl"],
  },
  laporankeuangan: {
    kode: "03.02.04",
    title: "LAPORAN KEUANGAN, SPJ",
    tambahRoute: "/uploadlaporankeuangan",
    jenisKeys: ["spjHibah", "kwitansi"],
  },

  // Contoh nanti buat Peraturan, SK Ka.LPPM (kode 03.02.02):
  // peraturan: {
  //   kode: "03.02.02",
  //   title: "PERATURAN, SK KA.LPPM",
  //   tambahRoute: "/uploadperaturan",
  //   jenisKeys: ["peraturan", "sk-ka-lppm"],
  // },
};